### ISSUE TITLE
PID for pro micro.

### ISSUE THREAD

**Issue by networkfusion** [dmadison/ArduinoXInput_Sparkfun#4]
I am not sure if this is valid, but all other boards seem to define a PID.

The Pro Micro is missing it, i.e. (highlighted added):

![image](https://user-images.githubusercontent.com/11439699/104511647-f1a5a000-55e4-11eb-9349-35c55ff2fb0e.png)

**Comment by dmadison** [comment]
It's there, look lower. SparkFun defined the 5V and 3.3V variants to have separate PIDs, so they're listed under each variant.

**Comment by networkfusion** [comment]
Ah, ok, thanks for the input. As I said I am new to the lib, and struggling to get something working (i.e. https://github.com/Ryzee119/n360) but closing as this is obviously not the issue.

Thanks for the speedy reply.
